Use tox in Travis tests
Because currently all builds fail with

  TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

deep in zope.interface (e.g. https://travis-ci.org/zopefoundation/zope.traversing/jobs/44704784)